class Constants {
  static final List<Map<String, String>> wordHintPairs = [
    {'word': 'cake', 'hint': 'A sweet dessert'},
    {'word': 'book', 'hint': 'Something to read'},
    {'word': 'tree', 'hint': 'Grows in a forest'},
    {'word': 'star', 'hint': 'Shines in the night sky'},
    {'word': 'moon', 'hint': 'Earth’s natural satellite'},
    {'word': 'fish', 'hint': 'Swims in the ocean'},
    {'word': 'bird', 'hint': 'Flies with wings'},
    {'word': 'door', 'hint': 'Entry to a room'},
    {'word': 'road', 'hint': 'Path for vehicles'},
    {'word': 'wind', 'hint': 'Moving air'},
    {'word': 'fire', 'hint': 'Burns with heat'},
    {'word': 'love', 'hint': 'Deep affection'},
    {'word': 'time', 'hint': 'Measured in hours'},
    {'word': 'home', 'hint': 'Where you live'},
    {'word': 'food', 'hint': 'Eaten for nourishment'},
    {'word': 'play', 'hint': 'Activity for fun'},
    {'word': 'work', 'hint': 'Done for a job'},
    {'word': 'rain', 'hint': 'Falls from clouds'},
    {'word': 'snow', 'hint': 'Frozen precipitation'},
    {'word': 'hill', 'hint': 'Small mountain'},
    {'word': 'lake', 'hint': 'Body of water'},
    {'word': 'ship', 'hint': 'Sails on seas'},
    {'word': 'gold', 'hint': 'Precious metal'},
    {'word': 'ring', 'hint': 'Worn on a finger'},
    {'word': 'ball', 'hint': 'Used in sports'},
    {'word': 'song', 'hint': 'Musical tune'},
    {'word': 'city', 'hint': 'Urban area'},
    {'word': 'town', 'hint': 'Smaller than a city'},
    {'word': 'path', 'hint': 'Trail to walk'},
    {'word': 'wall', 'hint': 'Barrier of a room'},
    {'word': 'lamp', 'hint': 'Provides light'},
    {'word': 'desk', 'hint': 'Furniture for work'},
    {'word': 'tree', 'hint': 'Has branches and leaves'},
    {'word': 'sand', 'hint': 'Found on beaches'},
    {'word': 'rock', 'hint': 'Hard earth material'},
    {'word': 'wave', 'hint': 'Ocean movement'},
    {'word': 'seed', 'hint': 'Grows into a plant'},
    {'word': 'root', 'hint': 'Anchors a plant'},
    {'word': 'leaf', 'hint': 'Green part of a plant'},
    {'word': 'stem', 'hint': 'Supports a plant'},
    {'word': 'deer', 'hint': 'Forest animal'},
    {'word': 'wolf', 'hint': 'Wild canine'},
    {'word': 'bear', 'hint': 'Large forest mammal'},
    {'word': 'lion', 'hint': 'King of the jungle'},
    {'word': 'tiger', 'hint': 'Striped big cat'},
    {'word': 'fox', 'hint': 'Cunning animal'},
    {'word': 'dog', 'hint': 'Loyal pet'},
    {'word': 'cat', 'hint': 'Feline companion'},
    {'word': 'horse', 'hint': 'Ridden by cowboys'},
    {'word': 'cow', 'hint': 'Provides milk'},
  ];
}
